### ISSUE TITLE
美化圖片加載不出來

### ISSUE THREAD

**Issue by ahhiisme** [sakarie9/DoL-Lyra#23]
不好意思打擾了，載了BESC+作弊+CSD+BJ特写的美化包，遊戲打開有作弊也有漢化，但圖片還是顯示原始的圖案，不知道這種情況要如何處理呢？
![image](https://github.com/sakarie9/DoL-Lyra/assets/143791571/d1b746ab-430d-4e57-8230-d17b0e5149aa)

**Comment by sakarie9** [comment]
移除mod `GameOriginalImagePack.mod.zip`

**Comment by ahhiisme** [comment]
謝謝!
