### ISSUE TITLE
忏悔室对话出现英文单词

### ISSUE THREAD

**Issue by Ham-desu** [sakarie9/DoL-Lyra#24]
![Screenshot_2024-01-16-08-25-10-231_com vrelnir DegreesOfLewdity lyra](https://github.com/sakarie9/DoL-Lyra/assets/11458903/cde12423-d1a9-48a4-a9cb-137d6b86711a)

频率：Once
前置：刚和悉尼结束忏悔室战斗

**Comment by sakarie9** [comment]
使用同样存档在 [汉化仓库在线版](https://eltirosto.github.io/Degrees-of-Lewdity-Chinese-Localization/) 这里试试

**Comment by HighSniper** [comment]
已经超过20steps的回溯限制了（悲）

**Comment by Ham-desu** [comment]
那我把这个issue给关了？选哪个？
