### ISSUE TITLE
大佬，感谢你的辛苦整理，喜欢的bj特写留海在新版本不见了

### ISSUE THREAD

**Issue by atd520** [sakarie9/DoL-Lyra#25]
如题，从0433版以后，感觉最适合bj特写的留海“齐整发尾型”不见了，变成了秃子。
![Screenshot_20240120-233435](https://github.com/sakarie9/DoL-Lyra/assets/117795230/dfedf042-7182-4eef-a798-804d674391cc)
求求让其恢复美貌吧，不胜感激。

**Comment by sakarie9** [comment]
某个版本的dol把 `img/hair/fringe/blunt sidelocks` 改成了 `img/hair/fringe/blunt locks`, BJ 里面没跟着改就光头了

**Comment by sakarie9** [comment]
84500ae

下次打包就有了

**Comment by atd520** [comment]
> 某个版本的dol把`img/hair/fringe/blunt sidelocks`没改成`img/hair/fringe/blunt locks`，BJ里面跟着改就光头了

嘿嘿，看到你这么详细的提示，我自己改了下文件名称就出来了，确实比之前版本多出个blunt locks，但是里面的文件确实多余的，正确文件在blunt sidelocks里面。话说bj特写停更真的好可惜，支持发型太少了。感谢大佬。

**Comment by atd520** [comment]
> [84500ae](https://github.com/sakarie9/DoL-Lyra/commit/84500ae9d3cb408ee2e240d4cc313e5643ddb127)
> 
> 下次资源有了

好吧，新版本依旧没有修复留海问题，也许你忘记了。

**Comment by sakarie9** [comment]
> > [84500ae](https://github.com/sakarie9/DoL-Lyra/commit/84500ae9d3cb408ee2e240d4cc313e5643ddb127)
> > 下次资源有了
> 
> 好吧，新版本依旧没有修复留海问题，也许你忘记了。

脚本写错了，新发的 0126.1 已经修好了
