### ISSUE TITLE
SUSATO版更换背景前景图片

### ISSUE THREAD

**Issue by amy41288** [sakarie9/DoL-Lyra#28]
如题，游戏内说明是替换img\detections档案夹内的图片，然而img目录内没有名为detections的档案夹，请问这样要怎么替换成自定义图片？

**Comment by sakarie9** [comment]
susato是作为mod打包进html的，想修改只能新建一个新的mod放入对应位置的图片然后加载

参考 [DoL_BeautySelectorAddonMod](https://github.com/Lyoko-Jeremie/DoL_BeautySelectorAddonMod)
