### ISSUE TITLE
巨鹰恋爱出现问题

### ISSUE THREAD

**Issue by ALyCE-hth** [sakarie9/DoL-Lyra#31]
无法与巨鹰达成恋人关系

**Comment by sakarie9** [comment]
> https://github.com/sakarie9/DoL-Lyra#%E7%96%91%E9%9A%BE%E8%A7%A3%E7%AD%94

“使用本整合出现各种问题时请先使用 汉化仓库 发布的版本，或是汉化仓库提供的 汉化在线版，测试是否同样出现问题”
