### ISSUE TITLE
不管下载哪个版本汉化都七零八散的怎么办😭😭

### ISSUE THREAD

**Issue by ThrenodyA0** [sakarie9/DoL-Lyra#32]
![IMG_3917](https://github.com/sakarie9/DoL-Lyra/assets/171177685/ca290d8a-1780-4952-b555-c67188044442)
![IMG_3918](https://github.com/sakarie9/DoL-Lyra/assets/171177685/9e8fa06a-473b-4d6d-9c33-7a9ccce08362)
![IMG_3919](https://github.com/sakarie9/DoL-Lyra/assets/171177685/6844eac9-b657-4ea5-8f60-3d9eb3749741)
就像这样⬆️
是用Safari下载的，下载zip到本地解压然后拷到ftp
以前三月份左右的时候下载过一次，都挺好，没有出现汉化问题
后来版本更新又找了新版本下载就这样了
不管下载哪个美化包版本都这样，救命😭😭😭

**Comment by ThrenodyA0** [comment]
另，使用汉化仓库的汉化在线版打开是没有这样的问题的

**Comment by sakarie9** [comment]
整合包不需要手动打汉化mod，去旁加载里卸掉

**Comment by ThrenodyA0** [comment]
!芜！原来是这样！之前用的版本一直没问题我都没发现我添加了汉化包，应该是一开始下载原版的时候加的，没想到会同步到其他版本里，谢谢！
