### ISSUE TITLE
罗宾码头后续事件报错

### ISSUE THREAD

**Issue by mirrormirroronwall** [sakarie9/DoL-Lyra#33]
整合包为DoL-0.4.7.5-Lyra-a2.0.2-cheat-csd-0524
选择安慰罗宾并离开后，孤儿院事件会报错
汉化仓库发布的版本中未出现该问题
![image](https://github.com/sakarie9/DoL-Lyra/assets/150267706/81efa06b-e50a-4a05-aec1-5e897ed3fd80)
![image](https://github.com/sakarie9/DoL-Lyra/assets/150267706/e2b73696-6dec-4fc7-9eae-88bedeec03f6)
[degrees-of-lewdity-20240604-181554.txt](https://github.com/user-attachments/files/15548631/degrees-of-lewdity-20240604-181554.txt)

**Comment by sakarie9** [comment]
![图片](https://github.com/sakarie9/DoL-Lyra/assets/20642596/173be12e-f5e2-48dd-8cb0-e6dbccee2144)

新版加载存档之后事件好像消失了
