### ISSUE TITLE
v0.4.7.5-alpha2.0.2-0605的BESC+作弊+CSD+BJ特写+WAX以及其他带有作弊标签的游戏会爆红

### ISSUE THREAD

**Issue by c1533** [sakarie9/DoL-Lyra#34]
在作弊的其他窗口会爆红
![Screenshot_20240612_152447](https://github.com/sakarie9/DoL-Lyra/assets/172475847/8076a85b-701b-4218-b526-b162709c80ff)
![Screenshot_20240612_152602](https://github.com/sakarie9/DoL-Lyra/assets/172475847/745540c7-bfe1-427a-9aef-528a53d7594b)

**Comment by c1533** [comment]
![Uploading Screenshot_20240612_152602.jpg…]()

**Comment by sakarie9** [comment]
［作弊扩展］不是整合包里的带的那个 Cheat 模组，请使用原版复现并向模组作者回报 Bug
