### ISSUE TITLE
美化包不显示，卸载了原图包的mod以后就没有图片了

### ISSUE THREAD

**Issue by asdfjmxx** [sakarie9/DoL-Lyra#35]
啊啊不好意思，为什么我下载了zip和美化包，然后也在mod 管理器里面卸载了原图包的mod 然后一刷新就显示不了图片了
![屏幕截图 2024-06-13 074400](https://github.com/sakarie9/DoL-Lyra/assets/172553443/4a19149d-5323-4f79-ba53-5dfe9b3f4c0d)

**Comment by sakarie9** [comment]
先更新，最新版已经是 `v0.4.7.5-alpha2.0.2` 了

**Comment by asdfjmxx** [comment]
> 先更新，最新版已经是 `v0.4.7.5-alpha2.0.2` 了

感谢！
