### ISSUE TITLE
汉化组提供的汉化版本没有img文件夹，这是哪个mod导致的

### ISSUE THREAD

**Issue by P0Zeratul** [sakarie9/DoL-Lyra#36]
如题，版本更新了我想自己装美化，但是汉化组提供的带modloader版本没有img文件夹，是哪个mod导致的还是其它什么原因

**Comment by sakarie9** [comment]
[GameOriginalImagePack](https://github.com/Eltirosto/Degrees-of-Lewdity-Chinese-Localization/releases/download/v0.5.0.5-chs-1.0.0a/GameOriginalImagePack-0.5.0.5.mod.zip)

解压出来 img 文件夹直接丢到 html 旁边然后往里面覆盖美化就行

**Comment by P0Zeratul** [comment]
好的，谢谢，我是想怎么反向给新的0.5.0.5装美化，所以问的这个问题
