### ISSUE TITLE
贴图错位问题

### ISSUE THREAD

**Issue by P0Zeratul** [sakarie9/DoL-Lyra#37]
![image](https://github.com/sakarie9/DoL-Lyra/assets/104356866/647b8f39-4063-440e-9296-00ebcbe7c741)
BESC+WAX的美化包在手持伞、包的时候会存在图所示的贴图错位，是美化包的问题么

**Comment by sakarie9** [comment]
错位就是新版本新增或者修改了贴图但是美化还没跟进，等美化更新

**Comment by P0Zeratul** [comment]
OK,THX
