### ISSUE TITLE
打开内衣下部分出现报错，无论是商店中的还是衣柜中的 

### ISSUE THREAD

**Issue by y5353030** [sakarie9/DoL-Lyra#38]

**Comment by y5353030** [comment]
看了一下在线版好像没有这个问题，我再排查下吧

**Comment by y5353030** [comment]
将我的存档导入在线版还是会报错：
0.5.0.6 Error (:: Hallways): <<doVersionCheck>>: cannot execute widget: 0.5.0.6 Error (:: Hallways): <<backComp>>: cannot execute widget: 0.5.0.6 Error (:: Hallways): <<npcPregnancyUpdater>>: cannot execute widget: 0.5.0.6 Error (:: Hallways): <<if>>: bad conditional expression in <<if>> clause: Cannot read properties of undefined (reading 'pregnancy')
推测可能是jj大小导致的

**Comment by sakarie9** [comment]
汉化组提供的这个 [在线版](https://eltirosto.github.io/Degrees-of-Lewdity-Chinese-Localization/) 吗

如果确定是没有其他 mod 的汉化原版还存在问题可以去汉化仓库反馈，这里解决不了游戏或者汉化的问题

**Comment by y5353030** [comment]
好的，我去反馈下
