### ISSUE TITLE
我無法使用mod加载器的远端加载的方式来加载一些mod

### ISSUE THREAD

**Issue by Hai-de** [sakarie9/DoL-Lyra#39]
我发现在这个v0.5.0.6-2.1.0a-0701版本的BESC+CSD+BJ特写+WAX(推荐)分支中无法加载modList.json文件中的mod列表,我不能确定这是什么原因
<img width="952" alt="螢幕擷取畫面 2024-07-13 192803" src="https://github.com/user-attachments/assets/99a3073f-3dd8-4d84-949a-4d30f54a6276">

**Comment by sakarie9** [comment]
试试汉化仓库的原版 ml

以及根据 [加载顺序](https://github.com/Lyoko-Jeremie/sugarcube-2-ModLoader/tree/2a914fc44ec2554c422fbc8de9dcd4ae88019b36#%E5%8A%A0%E8%BD%BD%E9%A1%BA%E5%BA%8F)，`modList.json` 只在web服务器下生效，直接打开 html 可能会不起作用

**Comment by Hai-de** [comment]
> 试试汉化仓库的原版 ml
> 
> 以及根据 [加载顺序](https://github.com/Lyoko-Jeremie/sugarcube-2-ModLoader/tree/2a914fc44ec2554c422fbc8de9dcd4ae88019b36#%E5%8A%A0%E8%BD%BD%E9%A1%BA%E5%BA%8F)，`modList.json` 只在web服务器下生效，直接打开 html 可能会不起作用

我使用python來搭建一个简易的web服务后,发现会无视美化只会加载mod列表的内容.

所以我使用汉化仓库中下载含模组加载器的游戏本体,把图片包GameOriginalImagePack.mod.zip中的img文件夹里面的内容替换成了BESC+CSD+BJ特写+WAX(推荐)分支中img内容,并加载了[Lyra-CombatStatusDisplay](https://github.com/DoL-Lyra/CombatStatusDisplay) [Lyra-Cheat](https://github.com/DoL-Lyra/Cheat) 这两个mod.

目前看起来正常的加载美化和mod内容,没有其他的事情应该可以关闭这个issues了
<img width="1236" alt="螢幕擷取畫面 2024-07-13 234852" src="https://github.com/user-attachments/assets/93d81f25-e587-4dfb-9c0b-817300609f8c">
